name: Manter Streamlit Acordado

on:
  schedule:
    - cron: '0 12 * * *' # Roda todos os dias
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer um ping no Streamlit
        run: |
          # Acessa a rota interna de saúde do Streamlit
          STATUS=$(curl -s https://observatorio-ati.streamlit.app/_stcore/health)
          
          # Mostra no log do GitHub se deu certo
          echo "Resposta do servidor: $STATUS"
          
          if [ "$STATUS" = "ok" ]; then
            echo "✅ Aplicativo está online e acordado!"
          else
            echo "⚠️ Resposta inesperada do servidor."
          fi